server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: consul
      port: 8500
    gateway:
      default-filters:
      - PrefixPath=/
      - name: CircuitBreaker
        args:
          name: default-fallback
          fallbackUri: forward:/fallback
      routes:
      # ======================
      - id: flashcard
        uri: lb://flashcard
        predicates:
        - Path=/flashcard/**
        filters:
        - StripPrefix=1
        - name: CircuitBreaker
          args:
            name: default-fallback
            fallbackUri: forward:/fallback/flashcard
      # ======================
      - id: quiz
        uri: lb://quiz
        predicates:
        - Path=/quiz/**
        filters:
        - StripPrefix=1
      # ======================
      - id: quiz-composite
        uri: lb://quiz-composite
        predicates:
        - Path=/composite/**
        filters:
        - StripPrefix=1
        - name: CircuitBreaker
          args:
            name: default-fallback
            fallbackUri: forward:/fallback
